// Generated by Selenium IDE
package testNG;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Testing123Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testing123() {
    driver.get("https://www.google.com/search?q=cars&sca_esv=596463110&sxsrf=ACQVn0_VBZUJ9QvZpbUxQaRm5FvQTshuPQ%3A1704690673789&source=hp&ei=8YObZc-_Lt_dseMP9reYiAM&iflsig=ANes7DEAAAAAZZuSAVDblewqEkY76oxqJ4wTSjUDMCdD&ved=0ahUKEwiP_L7Qg82DAxXfbmwGHfYbBjEQ4dUDCAo&uact=5&oq=cars&gs_lp=Egdnd3Mtd2l6IgRjYXJzMgoQABiABBiKBRhDMhAQABiABBiKBRhDGLEDGIMBMhAQABiABBiKBRhDGLEDGIMBMhAQABiABBiKBRhDGLEDGMkDMhAQLhiABBiKBRhDGLEDGIMBMhAQLhiABBiKBRhDGLEDGIMBMhAQLhiABBiKBRhDGLEDGIMBMhAQABiABBiKBRhDGLEDGIMBMgsQABiABBiKBRiSAzIKEC4YgAQYigUYQ0i-F1AAWJYKcAB4AJABAJgBeqAB2AOqAQMwLjS4AQPIAQD4AQHCAgoQIxiABBiKBRgnwgILEAAYgAQYigUYkQLCAhEQLhiABBixAxiDARjHARjRA8ICCxAAGIAEGLEDGIMBwgIFEAAYgATCAhYQLhiABBiKBRhDGLEDGIMBGMcBGNEDwgIQEC4YgAQYigUYQxjHARjRAw&sclient=gws-wiz");
    driver.findElement(By.cssSelector("#rso > .MjjYud:nth-child(1) .LC20lb")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".o-fznJzu:nth-child(3) > .o-cKuOoN .o-bXKmQE"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
